### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by kledula** [b-inary/wasm-postflop#14]
Hello! I'm wondering whats the right way to use the bounching effect?
It has 4boxes.
![image](https://github.com/b-inary/wasm-postflop/assets/140349271/8b3511a6-9e6c-4ae0-be57-0c52fdb739f1)
I filled them with UTG MP CO inverted ranges.
Then i inserted BB's calling range + BU's opening range.
![image](https://github.com/b-inary/wasm-postflop/assets/140349271/5958c2eb-5797-4319-a632-d9c1425c0ece)
This is how it looks. It seems that it takes 2 eternities. Did i make any mistakes?

**Comment by b-inary** [comment]
Aside from the fact that the bunching effect is only supported in Desktop Postflop, in 6-max games you should also enter SB's fold range. However, as the note in the screenshot says, enabling the bunching effect will *significantly* slow down the solver. I wouldn't recommend enabling it unless you are extremely interested in the difference between with and without the bunching effect.
