### ISSUE TITLE
 How to install front-end library

### ISSUE THREAD

**Issue by sunghyunkim2** [b-inary/wasm-postflop#16]
Thank you for releasing it as open source.

I installed the vue router library, but I can't build it because of a TypeScript-related error.

It works fine when installed using the same method in the desktop-postflop project, but since I am studying the web version, I would like to know how to install the library in the wasm-postflop project.

I tried to resolve the error on my own, but I felt it was impossible, so I'm asking a question. Thank you.

error code: TS7016: Could not find a declaration file for module './router/index.js'. '/Users/wasm-postflop/src/router/index.js' implicitly has an 'any' type.

**Comment by b-inary** [comment]
I'm sorry, but it seems difficult to give useful advice with your limited information. Please find a solution yourself, depending on your situation. Maybe you need to create a TypeScript file named `src/router/index.ts` instead of `index.js`.
