### ISSUE TITLE
sed -i doesn't work on osx

### ISSUE THREAD

**Issue by indigosquirrelio** [b-inary/wasm-postflop#2]
This is documenting an issue when building on OS X. Not familiar with frontend development yet, so maybe I'll add a proper fix later :)

For now in package.json, change the wasm:solver-patch line to:
```   
"wasm:solver-patch": "sed -i '' -e \"s/cachedInt32Memory0 = new Int32Array(wasm.memory.buffer)/cachedInt32Memory0 = new Uint32Array(wasm.memory.buffer)/\" ./pkg/solver-mt/solver.js ./pkg/solver-st/solver.js"
```

**Comment by b-inary** [comment]
I apologize for this very late response.

I cannot confirm this because I do not have a Mac, but the problem should have been fixed. Please reopen this issue if the problem persists.
