### ISSUE TITLE
[Feature request] Export/Import ranges

### ISSUE THREAD

**Issue by JbCourtois** [b-inary/wasm-postflop#4]
Having my predefined own ranges is a great feature ! :+1: 

Can we please have a button to export/import the whole tree ?
Same request for tree configurations.

**Comment by b-inary** [comment]
Understood, I will probably implement it within a week. Thanks for the suggestion!

**Comment by JbCourtois** [comment]
Great, thanks a lot ! 😊

**Comment by b-inary** [comment]
Implemented. If you find any problems, please let me know.
